version: "3"

volumes:
  home:

services:
  magneticod:
    build:
      context: .
      dockerfile: Dockerfile.magneticod
    volumes:
      - home:/home/magnetico

  magneticow:
    build:
      context: .
      dockerfile: Dockerfile.magneticow
    volumes:
      - home:/home/magnetico
    depends_on:
      # It doesn't necessarily "depend" on magneticod, but you would probably like to start them at the same time.
      - magneticod

    ports:
      - "8080:8080"
